# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Илья\Google Диск\Python\hello_pycharm\load_tiles_form.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_LoadTilesForm(object):
    def setupUi(self, LoadTilesForm):
        LoadTilesForm.setObjectName(_fromUtf8("LoadTilesForm"))
        LoadTilesForm.resize(584, 750)
        self.verticalLayout_3 = QtGui.QVBoxLayout(LoadTilesForm)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_5 = QtGui.QLabel(LoadTilesForm)
        self.label_5.setMinimumSize(QtCore.QSize(70, 0))
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_7.addWidget(self.label_5)
        self.project_le = QtGui.QLineEdit(LoadTilesForm)
        self.project_le.setObjectName(_fromUtf8("project_le"))
        self.horizontalLayout_7.addWidget(self.project_le)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_8 = QtGui.QLabel(LoadTilesForm)
        self.label_8.setMinimumSize(QtCore.QSize(70, 0))
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_13.addWidget(self.label_8)
        self.folder_le = QtGui.QLineEdit(LoadTilesForm)
        self.folder_le.setObjectName(_fromUtf8("folder_le"))
        self.horizontalLayout_13.addWidget(self.folder_le)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.load_kml_btn = QtGui.QPushButton(LoadTilesForm)
        self.load_kml_btn.setObjectName(_fromUtf8("load_kml_btn"))
        self.horizontalLayout_5.addWidget(self.load_kml_btn)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.groupBox = QtGui.QGroupBox(LoadTilesForm)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setMinimumSize(QtCore.QSize(40, 0))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.north_sb = QtGui.QDoubleSpinBox(self.groupBox)
        self.north_sb.setMinimumSize(QtCore.QSize(120, 0))
        self.north_sb.setDecimals(8)
        self.north_sb.setMinimum(-90.0)
        self.north_sb.setMaximum(90.0)
        self.north_sb.setObjectName(_fromUtf8("north_sb"))
        self.horizontalLayout.addWidget(self.north_sb)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout_11.addLayout(self.horizontalLayout)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setMinimumSize(QtCore.QSize(40, 0))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_3.addWidget(self.label_2)
        self.west_sb = QtGui.QDoubleSpinBox(self.groupBox)
        self.west_sb.setMinimumSize(QtCore.QSize(120, 0))
        self.west_sb.setDecimals(8)
        self.west_sb.setMinimum(-180.0)
        self.west_sb.setMaximum(180.0)
        self.west_sb.setObjectName(_fromUtf8("west_sb"))
        self.horizontalLayout_3.addWidget(self.west_sb)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_3)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setMinimumSize(QtCore.QSize(40, 0))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_4.addWidget(self.label_3)
        self.east_sb = QtGui.QDoubleSpinBox(self.groupBox)
        self.east_sb.setMinimumSize(QtCore.QSize(120, 0))
        self.east_sb.setDecimals(8)
        self.east_sb.setMinimum(-180.0)
        self.east_sb.setMaximum(180.0)
        self.east_sb.setObjectName(_fromUtf8("east_sb"))
        self.horizontalLayout_4.addWidget(self.east_sb)
        self.horizontalLayout_4.setStretch(1, 1)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem4)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setMinimumSize(QtCore.QSize(40, 0))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_2.addWidget(self.label_4)
        self.south_sb = QtGui.QDoubleSpinBox(self.groupBox)
        self.south_sb.setMinimumSize(QtCore.QSize(120, 0))
        self.south_sb.setDecimals(8)
        self.south_sb.setMinimum(-90.0)
        self.south_sb.setMaximum(90.0)
        self.south_sb.setObjectName(_fromUtf8("south_sb"))
        self.horizontalLayout_2.addWidget(self.south_sb)
        self.horizontalLayout_2.setStretch(1, 1)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_2)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(LoadTilesForm)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setMinimumSize(QtCore.QSize(60, 0))
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_8.addWidget(self.label_6)
        self.min_zoom_sl = QtGui.QSlider(self.groupBox_2)
        self.min_zoom_sl.setMaximum(19)
        self.min_zoom_sl.setOrientation(QtCore.Qt.Horizontal)
        self.min_zoom_sl.setObjectName(_fromUtf8("min_zoom_sl"))
        self.horizontalLayout_8.addWidget(self.min_zoom_sl)
        self.min_zoom_sb = QtGui.QSpinBox(self.groupBox_2)
        self.min_zoom_sb.setMaximum(19)
        self.min_zoom_sb.setObjectName(_fromUtf8("min_zoom_sb"))
        self.horizontalLayout_8.addWidget(self.min_zoom_sb)
        self.horizontalLayout_8.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setMinimumSize(QtCore.QSize(60, 0))
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_9.addWidget(self.label_7)
        self.max_zoom_sl = QtGui.QSlider(self.groupBox_2)
        self.max_zoom_sl.setMaximum(19)
        self.max_zoom_sl.setOrientation(QtCore.Qt.Horizontal)
        self.max_zoom_sl.setObjectName(_fromUtf8("max_zoom_sl"))
        self.horizontalLayout_9.addWidget(self.max_zoom_sl)
        self.max_zoom_sb = QtGui.QSpinBox(self.groupBox_2)
        self.max_zoom_sb.setMaximum(19)
        self.max_zoom_sb.setObjectName(_fromUtf8("max_zoom_sb"))
        self.horizontalLayout_9.addWidget(self.max_zoom_sb)
        self.horizontalLayout_9.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.calc_tile_cnt_btn = QtGui.QPushButton(LoadTilesForm)
        self.calc_tile_cnt_btn.setObjectName(_fromUtf8("calc_tile_cnt_btn"))
        self.horizontalLayout_6.addWidget(self.calc_tile_cnt_btn)
        self.download_btn = QtGui.QPushButton(LoadTilesForm)
        self.download_btn.setObjectName(_fromUtf8("download_btn"))
        self.horizontalLayout_6.addWidget(self.download_btn)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.log_te = QtGui.QTextEdit(LoadTilesForm)
        self.log_te.setUndoRedoEnabled(False)
        self.log_te.setReadOnly(True)
        self.log_te.setOverwriteMode(True)
        self.log_te.setObjectName(_fromUtf8("log_te"))
        self.verticalLayout_3.addWidget(self.log_te)

        self.retranslateUi(LoadTilesForm)
        QtCore.QObject.connect(self.min_zoom_sl, QtCore.SIGNAL(_fromUtf8("sliderMoved(int)")), self.min_zoom_sb.setValue)
        QtCore.QObject.connect(self.max_zoom_sl, QtCore.SIGNAL(_fromUtf8("sliderMoved(int)")), self.max_zoom_sb.setValue)
        QtCore.QObject.connect(self.min_zoom_sb, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.min_zoom_sl.setValue)
        QtCore.QObject.connect(self.max_zoom_sb, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.max_zoom_sl.setValue)
        QtCore.QMetaObject.connectSlotsByName(LoadTilesForm)

    def retranslateUi(self, LoadTilesForm):
        LoadTilesForm.setWindowTitle(_translate("LoadTilesForm", "Download tiles", None))
        self.label_5.setText(_translate("LoadTilesForm", "ProjectName:", None))
        self.label_8.setText(_translate("LoadTilesForm", "Folder:", None))
        self.load_kml_btn.setText(_translate("LoadTilesForm", "  Load coordinates from kml  ", None))
        self.groupBox.setTitle(_translate("LoadTilesForm", "Coordinates:", None))
        self.label.setText(_translate("LoadTilesForm", "North:", None))
        self.label_2.setText(_translate("LoadTilesForm", "West:", None))
        self.label_3.setText(_translate("LoadTilesForm", "East:", None))
        self.label_4.setText(_translate("LoadTilesForm", "South:", None))
        self.groupBox_2.setTitle(_translate("LoadTilesForm", "Zoom Range", None))
        self.label_6.setText(_translate("LoadTilesForm", "Min zoom:", None))
        self.label_7.setText(_translate("LoadTilesForm", "Max zoom:", None))
        self.calc_tile_cnt_btn.setText(_translate("LoadTilesForm", "Calculate tile count:", None))
        self.download_btn.setText(_translate("LoadTilesForm", "   Load tiles and create kml    ", None))

